# version: '2.3.3'
services:
  api:
    build: . #/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:DmOa44RzQQVBwMBJDxio@foodbuy-database.cyvsz9rkrvyq.eu-west-3.rds.amazonaws.com/foodbuy
      XXX_HOST: xxx
    ports:
      - '3000:3000'
    # depends_on:
    #   - database

  # database:
  #   image: postgres
  #   environment: 
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: tibo
  #     POSTGRES_PASSWORD: whitebeard
  #   ports:
  #     - '5432:5432'
    
