"""empty message

Revision ID: 9107523fb97a
Revises: e7ddc22f4a50
Create Date: 2022-04-07 16:22:25.041092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9107523fb97a'
down_revision = 'e7ddc22f4a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('purchases_price_key', 'purchases', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('purchases_price_key', 'purchases', ['price'])
    # ### end Alembic commands ###
